name: Android CI

on:
  push:
    branches: master
    paths-ignore: '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
    - name: Check out
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: 1
        ref: master

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'jetbrains'
        java-version: 21
        check-latest: true

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Upload CI module zip as artifact zip
      uses: actions/upload-artifact@v4
      with:
        name: PlayIntegrityFix_${{ github.run_number }}-inject-s
        path: 'module/*'
        compression-level: 9
