name: Dependency Review

on:
  pull_request:
    branches: [master]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          retry-on-snapshot-warnings: true
          retry-on-snapshot-warnings-timeout: 600
          fail-on-severity: moderate
          allow-licenses: |
            Apache-2.0
            MIT
            BSD-2-Clause
            BSD-3-Clause
            GPL-3.0
            LGPL-2.1
          deny-licenses: |
            GPL-2.0
            AGPL-3.0
          comment-summary-in-pr: always
          config-file: .github/dependency-review-config.yml
