name: Performance Monitoring

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 2 * * 0'

jobs:
  benchmark:
    name: Performance Benchmark
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
          build-scan-terms-of-use-agree: 'yes'

      - name: Run build performance tests
        run: |
          echo "Measuring build performance..."
          time ./gradlew clean assembleDebug --scan --profile
          time ./gradlew clean assembleRelease --scan --profile

      - name: Upload build profiles
        uses: actions/upload-artifact@v4
        with:
          name: build-profiles-${{ github.run_number }}
          path: build/reports/profile/
          retention-days: 14

      - name: Build size analysis
        run: |
          ./gradlew assembleRelease --scan
          find . -name "*.apk" -exec ls -lh {} \;
          find . -name "*.aab" -exec ls -lh {} \;

  memory-analysis:
    name: Memory Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Memory profiling build
        env:
          GRADLE_OPTS: -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=build/
        run: ./gradlew assembleDebug --scan --max-workers=1

      - name: Analyze build memory usage
        run: |
          echo "Gradle daemon memory usage:"
          ps aux | grep gradle || true
          echo "Build directory size:"
          du -sh build/ || true

  dependency-analysis:
    name: Dependency Size Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Analyze dependencies
        run: |
          ./gradlew dependencies --scan
          ./gradlew dependencyInsight --dependency androidx.core --scan

      - name: Generate dependency tree
        run: ./gradlew htmlDependencyReport --scan

      - name: Upload dependency reports
        uses: actions/upload-artifact@v4
        with:
          name: dependency-analysis
          path: build/reports/project/dependencies/
          retention-days: 7
